# Generated by Django 5.1.5 on 2025-02-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_dead_line_dt_task_finished_dt_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
